### ISSUE TITLE
[INFO] schema.graphql

### ISSUE THREAD

**Issue by GuillaumeUnice** [taion/relay-todomvc#16]
Hi,
I just want to know, whether your Basic Types GraphQL (https://github.com/taion/relay-todomvc/blob/master/src/data/schema.graphql) is declared for documentation or it's really use it?
Because I don't see, wherever can be use it.

Best regards,
Great job

**Comment by taion** [comment]
This is for TodoMVC. This code works fine, but it's just a toy demo thing intended to demonstrate the use of GraphQL and Relay.
