### ISSUE TITLE
where to point browser 

### ISSUE THREAD

**Issue by Aneeskhan** [taion/relay-todomvc#2]
I have git clone it then 
npm install
then
npm start
 then i point my browser to
localhost:3000 OR localhost:3000/#/ OR localhost:3000/#/active

but not working (http://localhost:3000/ net::ERR_CONNECTION_REFUSED ), where is Port 3000 Config?

**Comment by taion** [comment]
The Webpack dev server runs on port 8080 by default: https://github.com/node-inspector/node-inspector

**Comment by Aneeskhan** [comment]
http://localhost:8080/relay-todomvc or 
http://localhost:8080/relay-todomvc/#/active or 
http://localhost:8080/relay-todomvc/#/completed or 

with Port 8080 above routes are also not working

**Comment by taion** [comment]
See the updated README: https://github.com/taion/relay-todomvc#usage

**Comment by Aneeskhan** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/10149367/9770879/fc9a1cfe-574b-11e5-821b-18ec29b94970.png)

**Comment by taion** [comment]
It works for me. Make sure you're not running something else on port 8080, or otherwise are running with the correct dependencies.

**Comment by Aneeskhan** [comment]
complete pointing link is :http://localhost:8080/bundle#/ OR with route http://localhost:8080/bundle#/active
