### ISSUE TITLE
SSR causes duplicate graphql requests

### ISSUE THREAD

**Issue by hamza-openinvest** [taion/relay-todomvc#22]
I'm really interested in using Relay for a new project I'm building, and after testing out `isomorphic-react-router` it seems the spiritual successor is `found-relay` with SSR. I tried out the `found-modern-universal` branch locally, and my biggest concern is that the number of graphql requests to the server would double on initial page load. Besides being bad for the server, that's not great for the client either, and should technically be unnecessary since the client already has all the data it should need inside `window.__RELAY_RECORDS__` from what I can see.

Given this, there are a few possibilities for what's happening:
1. This is a known issue, and perhaps already on your roadmap to add/fix?
2. This is a bug that I'm experiencing that isn't known -- seems unlikely since I've only added some debugging code so far, but maybe I have an unsupported version of node/npm/whatever.
3. This is totally unavoidable with Relay Modern -- I really hope this isn't the case.

I'm curious which one of those it is, and if there is an existing or forthcoming solution.

Thanks!

**Comment by taion** [comment]
Oh, it's a bug with this example that I hadn't noticed. I forgot that Relay modern didn't go to the store.

**Comment by hamza-openinvest** [comment]
Ah cool, is that an easy fix? Anything I can help with?

**Comment by taion** [comment]
My approach is wrong – I should be doing the caching at the network request level, not at the store level. It's not especially involved.

**Comment by taion** [comment]
Fixed in https://github.com/taion/relay-todomvc/commit/180692faf9cb5d1186031ceea6f40149f1e52e7f

cc @staylor

**Comment by taion** [comment]
The real answer is that someone open-sources a more robust version of what I wrote, but what I have is enough to illustrate what this demo is supposed to do, I think.

**Comment by hamza-openinvest** [comment]
Tried it your fix and it works as expected, thanks! Your solution is interesting, it relies on relay making the same requests, and in the same order, on the server as it does on the client for the initial render. Do you happen to know if that is more or less guaranteed to work with Relay in general, or will that break in some cases you know of?

Also, I'm very curious about what you'd consider a robust/production-ready solution for Relay SSR...

**Comment by taion** [comment]
See https://github.com/facebook/relay/issues/1881

There's no reason your requests should go out-of-order though
