### ISSUE TITLE
Confusion on the Fetcher class

### ISSUE THREAD

**Issue by rklhui** [taion/relay-todomvc#24]
Excellent example on universal app react + relay modern! But I am a bit confused on the following code:
```
export class ServerFetcher extends FetcherBase {
  constructor(url) {
    super(url);

    this.payloads = [];
  }

  async fetch(...args) {
    const i = this.payloads.length;
    this.payloads.push(null);
    const payload = await super.fetch(...args);
    this.payloads[i] = payload;
    return payload;
  }

  toJSON() {
    return this.payloads;
  }
}

export class ClientFetcher extends FetcherBase {
  constructor(url, payloads) {
    super(url);

    this.payloads = payloads;
  }

  async fetch(...args) {
    if (this.payloads.length) {
      return this.payloads.shift();
    }

    return super.fetch(...args);
  }
}
```
Why do you need to push a null then replace and second to last payload in the ServerFetcher, and why do you need to shift() the payloads for the ClientFetch? Please help me clear up my mind.
Thanks.

**Comment by taion** [comment]
I push a `null` to avoid having a sparse array. I fill in the second-to-last payload just to replace that `null` with the actual value.

I use `shift()` in `ClientFetcher` to make sure I only use each cached payload exactly once.

See https://github.com/4Catalyzer/relay-fetch/pull/1 for a clearer version of this code.

**Comment by taion** [comment]
With @damassi's help, the SSR example now uses `ReactRelayNetworkModern` instead of the old `Fetcher` abstraction.
