### ISSUE TITLE
createInitialFarceRouter with hot reloading

### ISSUE THREAD

**Issue by tomconroy** [taion/relay-todomvc#25]
Is it possible to hot-reload routes created with `createInitialFarceRouter`?

The [example](https://github.com/4Catalyzer/found/blob/master/examples/hot-reloading/src/BrowserRouter.js) exports the equivalent `Router` component as `hot`. But I don't see how this is possible using `createInitialFarceRouter`.

I've had mixed success wrapping each route component with `hot` – some updates work and others don't, with and without mysterious errors.

**Comment by taion** [comment]
That `hot(module)` isn't for hot-reloading route configs. It's for hot-reloading the app as a whole. You can apply it to whatever your top-level export is. Your route config should always be amenable to `hotRouteConfig` per https://github.com/4Catalyzer/found#hot-reloading. This could be a function that wraps the `createInitialFarceRouter` call or whatever.

That said it sounds sort of weird to use SSR and hot reloading at the same time.
