### ISSUE TITLE
Warning: You cannot PUSH the same path using hash history

### ISSUE THREAD

**Issue by Aneeskhan** [taion/relay-todomvc#4]
if i click again on same route Link this happen any suggestion?

i read your comments on https://github.com/rackt/history/pull/43   
and on 
https://github.com/rackt/history/issues/178     
but unable to figure out solution 
any suggestion to fix this?

**Comment by taion** [comment]
This got fixed by the relevant history changes to replace the `PUSH` with a `REPLACE`.

**Comment by Aneeskhan** [comment]
any example code? or where to change ?
i have try this one
 if (nextPath === prevPath && deepEqual(location.state, nextLocation.state))
 but still warning in console

**Comment by taion** [comment]
Wait for the history upgrade on the React Router side.
