### ISSUE TITLE
There is no server.js

### ISSUE THREAD

**Issue by Aneeskhan** [taion/relay-todomvc#5]
![screenshot 50](https://cloud.githubusercontent.com/assets/10149367/14171994/6027cc82-f74f-11e5-8382-b6820f8adf4a.png)

In you TodoMVC example there is no server.js so what best place to put this code to run mongodb and Graphql. OR IF any full example of todoMVC with mongodb and grapgql you have send me the repo link

Thanks

**Comment by taion** [comment]
This example is in-browser only. There is no server component.
